# Generated by Django 5.2.4 on 2025-07-14 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fatherName', models.CharField(max_length=20, null=True)),
                ('motherName', models.CharField(max_length=20, null=True)),
                ('contact', models.BigIntegerField()),
                ('dob', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=50)),
                ('yos', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
