# Generated by Django 5.2.4 on 2025-07-15 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='email',
            new_name='student',
        ),
    ]
