# Generated by Django 5.2.4 on 2025-07-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_courses_enrollment_students_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='semester',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='courses',
            name='year',
            field=models.IntegerField(default=1),
        ),
    ]
