# Generated by Django 5.2.4 on 2025-07-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_courses_semester_courses_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='semester',
            field=models.IntegerField(default=1),
        ),
    ]
