# Generated by Django 5.2.4 on 2025-07-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_students_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('ongoing', 'ongoing'), ('pass', 'pass'), ('fail', 'fail')], max_length=7),
        ),
    ]
